// Generated by Supabase MCP from project dicufymnejhrkrakgluu.
// DO NOT EDIT MANUALLY.
// To regenerate: call mcp__claude_ai_Supabase__generate_typescript_types via the active MCP.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_settings: {
        Row: {
          id: string
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          id?: string
          key: string
          updated_at?: string
          updated_by?: string | null
          value: Json
        }
        Update: {
          id?: string
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "app_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      card_quiz_questions: {
        Row: {
          card_id: string
          choice_a: string
          choice_b: string
          choice_c: string
          choice_d: string
          correct_choice: string
          created_at: string
          id: string
          question_text: string
        }
        Insert: {
          card_id: string
          choice_a: string
          choice_b: string
          choice_c: string
          choice_d: string
          correct_choice: string
          created_at?: string
          id?: string
          question_text: string
        }
        Update: {
          card_id?: string
          choice_a?: string
          choice_b?: string
          choice_c?: string
          choice_d?: string
          correct_choice?: string
          created_at?: string
          id?: string
          question_text?: string
        }
        Relationships: [
          {
            foreignKeyName: "card_quiz_questions_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "review_cards"
            referencedColumns: ["id"]
          },
        ]
      }
      card_reviews: {
        Row: {
          card_id: string
          created_at: string
          difficulty: number
          due_at: string
          fsrs_params_version: number
          id: string
          last_reviewed_at: string | null
          review_count: number
          stability: number
          state: Database["public"]["Enums"]["card_review_state"]
          student_id: string
        }
        Insert: {
          card_id: string
          created_at?: string
          difficulty?: number
          due_at?: string
          fsrs_params_version?: number
          id?: string
          last_reviewed_at?: string | null
          review_count?: number
          stability?: number
          state?: Database["public"]["Enums"]["card_review_state"]
          student_id: string
        }
        Update: {
          card_id?: string
          created_at?: string
          difficulty?: number
          due_at?: string
          fsrs_params_version?: number
          id?: string
          last_reviewed_at?: string | null
          review_count?: number
          stability?: number
          state?: Database["public"]["Enums"]["card_review_state"]
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "card_reviews_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "review_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_reviews_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "card_reviews_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      classes: {
        Row: {
          archived_at: string | null
          created_at: string
          id: string
          invite_code: string
          name: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          id?: string
          invite_code: string
          name: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          id?: string
          invite_code?: string
          name?: string
        }
        Relationships: []
      }
      coop_quest_instances: {
        Row: {
          created_at: string
          id: string
          quest_id: string
          reviewed_at: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["coop_instance_status"]
          submitted_at: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          quest_id: string
          reviewed_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["coop_instance_status"]
          submitted_at?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          quest_id?: string
          reviewed_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["coop_instance_status"]
          submitted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "coop_quest_instances_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_unlocks: {
        Row: {
          class_id: string
          id: string
          lesson_id: string
          unlocked_at: string
        }
        Insert: {
          class_id: string
          id?: string
          lesson_id: string
          unlocked_at?: string
        }
        Update: {
          class_id?: string
          id?: string
          lesson_id?: string
          unlocked_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lesson_unlocks_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_unlocks_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lesson_card_counts"
            referencedColumns: ["lesson_id"]
          },
          {
            foreignKeyName: "lesson_unlocks_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      lessons: {
        Row: {
          created_at: string
          id: string
          lesson_number: number
          title: string
        }
        Insert: {
          created_at?: string
          id?: string
          lesson_number: number
          title: string
        }
        Update: {
          created_at?: string
          id?: string
          lesson_number?: number
          title?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          data: Json | null
          id: string
          override_quiet_hours: boolean
          pushed_at: string | null
          read_at: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          data?: Json | null
          id?: string
          override_quiet_hours?: boolean
          pushed_at?: string | null
          read_at?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          data?: Json | null
          id?: string
          override_quiet_hours?: boolean
          pushed_at?: string | null
          read_at?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          age: number | null
          avatar_url: string | null
          class_id: string | null
          created_at: string
          current_rank: number
          email: string
          full_name: string
          id: string
          interest_tags: string[] | null
          last_active_at: string | null
          learning_velocity: number
          role: Database["public"]["Enums"]["user_role"]
          xp_total: number
        }
        Insert: {
          age?: number | null
          avatar_url?: string | null
          class_id?: string | null
          created_at?: string
          current_rank?: number
          email: string
          full_name: string
          id: string
          interest_tags?: string[] | null
          last_active_at?: string | null
          learning_velocity?: number
          role: Database["public"]["Enums"]["user_role"]
          xp_total?: number
        }
        Update: {
          age?: number | null
          avatar_url?: string | null
          class_id?: string | null
          created_at?: string
          current_rank?: number
          email?: string
          full_name?: string
          id?: string
          interest_tags?: string[] | null
          last_active_at?: string | null
          learning_velocity?: number
          role?: Database["public"]["Enums"]["user_role"]
          xp_total?: number
        }
        Relationships: [
          {
            foreignKeyName: "profiles_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
      push_tokens: {
        Row: {
          created_at: string
          expo_push_token: string
          id: string
          last_used_at: string
          platform: Database["public"]["Enums"]["push_platform"]
          user_id: string
        }
        Insert: {
          created_at?: string
          expo_push_token: string
          id?: string
          last_used_at?: string
          platform: Database["public"]["Enums"]["push_platform"]
          user_id: string
        }
        Update: {
          created_at?: string
          expo_push_token?: string
          id?: string
          last_used_at?: string
          platform?: Database["public"]["Enums"]["push_platform"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_acceptances: {
        Row: {
          accepted_at: string
          completed_at: string | null
          id: string
          instance_id: string | null
          quest_id: string
          quest_type: Database["public"]["Enums"]["quest_type"]
          status: Database["public"]["Enums"]["quest_acceptance_status"]
          student_id: string
        }
        Insert: {
          accepted_at?: string
          completed_at?: string | null
          id?: string
          instance_id?: string | null
          quest_id: string
          quest_type: Database["public"]["Enums"]["quest_type"]
          status?: Database["public"]["Enums"]["quest_acceptance_status"]
          student_id: string
        }
        Update: {
          accepted_at?: string
          completed_at?: string | null
          id?: string
          instance_id?: string | null
          quest_id?: string
          quest_type?: Database["public"]["Enums"]["quest_type"]
          status?: Database["public"]["Enums"]["quest_acceptance_status"]
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quest_acceptances_instance_id_fkey"
            columns: ["instance_id"]
            isOneToOne: false
            referencedRelation: "coop_quest_instances"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_acceptances_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_acceptances_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_acceptances_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_submissions: {
        Row: {
          acceptance_id: string | null
          ai_likelihood_score: number | null
          id: string
          instance_id: string | null
          reviewed_at: string | null
          status: Database["public"]["Enums"]["quest_submission_status"]
          submitted_at: string
          submitted_by: string
          teacher_feedback: string | null
          text_content: string | null
          word_count: number | null
        }
        Insert: {
          acceptance_id?: string | null
          ai_likelihood_score?: number | null
          id?: string
          instance_id?: string | null
          reviewed_at?: string | null
          status?: Database["public"]["Enums"]["quest_submission_status"]
          submitted_at?: string
          submitted_by: string
          teacher_feedback?: string | null
          text_content?: string | null
          word_count?: number | null
        }
        Update: {
          acceptance_id?: string | null
          ai_likelihood_score?: number | null
          id?: string
          instance_id?: string | null
          reviewed_at?: string | null
          status?: Database["public"]["Enums"]["quest_submission_status"]
          submitted_at?: string
          submitted_by?: string
          teacher_feedback?: string | null
          text_content?: string | null
          word_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "quest_submissions_acceptance_id_fkey"
            columns: ["acceptance_id"]
            isOneToOne: false
            referencedRelation: "quest_acceptances"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_submissions_instance_id_fkey"
            columns: ["instance_id"]
            isOneToOne: false
            referencedRelation: "coop_quest_instances"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_submissions_submitted_by_fkey"
            columns: ["submitted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_submissions_submitted_by_fkey"
            columns: ["submitted_by"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quests: {
        Row: {
          availability_mode: Database["public"]["Enums"]["quest_availability_mode"]
          class_id: string
          closed_at: string | null
          created_at: string
          description: string
          expires_at: string | null
          id: string
          max_instances: number | null
          max_team_size: number | null
          quest_type: Database["public"]["Enums"]["quest_type"]
          title: string
          word_limit_min: number | null
          xp_reward: number
        }
        Insert: {
          availability_mode?: Database["public"]["Enums"]["quest_availability_mode"]
          class_id: string
          closed_at?: string | null
          created_at?: string
          description?: string
          expires_at?: string | null
          id?: string
          max_instances?: number | null
          max_team_size?: number | null
          quest_type: Database["public"]["Enums"]["quest_type"]
          title: string
          word_limit_min?: number | null
          xp_reward: number
        }
        Update: {
          availability_mode?: Database["public"]["Enums"]["quest_availability_mode"]
          class_id?: string
          closed_at?: string | null
          created_at?: string
          description?: string
          expires_at?: string | null
          id?: string
          max_instances?: number | null
          max_team_size?: number | null
          quest_type?: Database["public"]["Enums"]["quest_type"]
          title?: string
          word_limit_min?: number | null
          xp_reward?: number
        }
        Relationships: [
          {
            foreignKeyName: "quests_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
      review_attempts: {
        Row: {
          answered_at: string
          card_id: string
          card_review_state_at_answer: Database["public"]["Enums"]["card_review_state"]
          id: string
          is_correct: boolean
          quiz_question_id: string
          selected_choice: string
          student_id: string
          xp_awarded: number
        }
        Insert: {
          answered_at?: string
          card_id: string
          card_review_state_at_answer: Database["public"]["Enums"]["card_review_state"]
          id?: string
          is_correct: boolean
          quiz_question_id: string
          selected_choice: string
          student_id: string
          xp_awarded?: number
        }
        Update: {
          answered_at?: string
          card_id?: string
          card_review_state_at_answer?: Database["public"]["Enums"]["card_review_state"]
          id?: string
          is_correct?: boolean
          quiz_question_id?: string
          selected_choice?: string
          student_id?: string
          xp_awarded?: number
        }
        Relationships: [
          {
            foreignKeyName: "review_attempts_card_id_fkey"
            columns: ["card_id"]
            isOneToOne: false
            referencedRelation: "review_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_attempts_quiz_question_id_fkey"
            columns: ["quiz_question_id"]
            isOneToOne: false
            referencedRelation: "card_quiz_questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_attempts_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_attempts_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      review_cards: {
        Row: {
          body: string
          created_at: string
          headline: string
          id: string
          lesson_id: string
          position: number
        }
        Insert: {
          body?: string
          created_at?: string
          headline: string
          id?: string
          lesson_id: string
          position?: number
        }
        Update: {
          body?: string
          created_at?: string
          headline?: string
          id?: string
          lesson_id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "review_cards_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lesson_card_counts"
            referencedColumns: ["lesson_id"]
          },
          {
            foreignKeyName: "review_cards_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          },
        ]
      }
      student_assessments: {
        Row: {
          english_proficiency_cefr: string | null
          english_proficiency_pearson: number | null
          id: string
          student_id: string
          updated_at: string
        }
        Insert: {
          english_proficiency_cefr?: string | null
          english_proficiency_pearson?: number | null
          id?: string
          student_id: string
          updated_at?: string
        }
        Update: {
          english_proficiency_cefr?: string | null
          english_proficiency_pearson?: number | null
          id?: string
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "student_assessments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_assessments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      teacher_notes: {
        Row: {
          created_at: string
          id: string
          note: string
          student_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          note: string
          student_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          note?: string
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "teacher_notes_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "teacher_notes_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      xp_ledger: {
        Row: {
          amount: number
          created_at: string
          id: string
          reason: string
          source_id: string | null
          source_table: string | null
          student_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          reason: string
          source_id?: string | null
          source_table?: string | null
          student_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          reason?: string
          source_id?: string | null
          source_table?: string | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "xp_ledger_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "xp_ledger_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      lesson_card_counts: {
        Row: {
          card_count: number | null
          lesson_id: string | null
          question_count: number | null
        }
        Relationships: []
      }
      public_profiles: {
        Row: {
          age: number | null
          avatar_url: string | null
          class_id: string | null
          created_at: string | null
          current_rank: number | null
          full_name: string | null
          id: string | null
          interest_tags: string[] | null
          learning_velocity: number | null
          role: Database["public"]["Enums"]["user_role"] | null
          xp_total: number | null
        }
        Insert: {
          age?: number | null
          avatar_url?: string | null
          class_id?: string | null
          created_at?: string | null
          current_rank?: number | null
          full_name?: string | null
          id?: string | null
          interest_tags?: string[] | null
          learning_velocity?: number | null
          role?: Database["public"]["Enums"]["user_role"] | null
          xp_total?: number | null
        }
        Update: {
          age?: number | null
          avatar_url?: string | null
          class_id?: string | null
          created_at?: string | null
          current_rank?: number | null
          full_name?: string | null
          id?: string | null
          interest_tags?: string[] | null
          learning_velocity?: number | null
          role?: Database["public"]["Enums"]["user_role"] | null
          xp_total?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      admin_create_teacher: {
        Args: { p_email: string; p_full_name: string; p_password: string }
        Returns: string
      }
      compute_rank_from_xp: { Args: { xp: number }; Returns: number }
      get_registration_state: { Args: never; Returns: Json }
      is_registration_open: { Args: never; Returns: boolean }
      is_teacher: { Args: { uid?: string }; Returns: boolean }
      list_review_session: { Args: never; Returns: Json }
      lookup_class_by_invite: {
        Args: { code: string }
        Returns: {
          id: string
          name: string
        }[]
      }
      recompute_learning_velocity: { Args: never; Returns: Json }
      register_student: {
        Args: {
          p_age: number
          p_class_id: string
          p_email: string
          p_full_name: string
          p_user_id: string
        }
        Returns: Json
      }
      submit_mcq_answer: {
        Args: { p_quiz_question_id: string; p_selected_choice: string }
        Returns: Json
      }
      unlock_lesson_cards: {
        Args: { p_class_id: string; p_lesson_id: string }
        Returns: Json
      }
      user_class_id: { Args: { uid?: string }; Returns: string }
      users_share_class: { Args: { a: string; b: string }; Returns: boolean }
    }
    Enums: {
      card_review_state: "new" | "learning" | "review" | "relearning"
      coop_instance_status: "active" | "submitted" | "passed" | "disbanded"
      push_platform: "ios" | "android" | "web"
      quest_acceptance_status:
        | "active"
        | "submitted"
        | "passed"
        | "failed"
        | "enrolled"
        | "disbanded"
      quest_availability_mode:
        | "open"
        | "timed"
        | "whole_class"
        | "limited_instances"
      quest_submission_status: "pending_review" | "passed" | "failed"
      quest_type: "solo" | "coop" | "daily_quiz"
      user_role: "teacher" | "student"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      card_review_state: ["new", "learning", "review", "relearning"],
      coop_instance_status: ["active", "submitted", "passed", "disbanded"],
      push_platform: ["ios", "android", "web"],
      quest_acceptance_status: [
        "active",
        "submitted",
        "passed",
        "failed",
        "enrolled",
        "disbanded",
      ],
      quest_availability_mode: [
        "open",
        "timed",
        "whole_class",
        "limited_instances",
      ],
      quest_submission_status: ["pending_review", "passed", "failed"],
      quest_type: ["solo", "coop", "daily_quiz"],
      user_role: ["teacher", "student"],
    },
  },
} as const
